title: WASH PRO CRM
description: Local CRM/SCADA for self-service car washes on Dynamic API Platform
url: https://wash-pro.github.io
baseurl: /WASH-PRO-CRM

markdown: GFM
permalink: pretty
lang: en

plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-redirect-from

relative_links:
  enabled: true
  collections: true

exclude:
  - Gemfile
  - Gemfile.lock

defaults:
  - scope:
      path: "en"
      type: "pages"
    values:
      lang: en
  - scope:
      path: "ru"
      type: "pages"
    values:
      lang: ru
