import { sanitizeSerial } from './post-device.js';

interface PostAclRow {
  mqttLogin: string;
  serialNumber: string;
}

/** ACL Mosquitto: system — всё; пост — только топики своего serial. */
export function buildMqttAclFile(crmUser: string, posts: PostAclRow[], devicePrefix: string): string {
  const prefix = devicePrefix.trim() || 'washpro';
  const lines = [
    `# Generated by message-processor — do not edit manually`,
    `user ${crmUser}`,
    'topic readwrite #',
    '',
  ];

  const seenLogins = new Set<string>();
  for (const post of posts) {
    const login = post.mqttLogin.trim();
    const serial = sanitizeSerial(post.serialNumber);
    if (!login || !serial || seenLogins.has(login)) continue;
    seenLogins.add(login);

    lines.push(`user ${login}`);
    lines.push(`topic read ${prefix}/${serial}/#`);
    lines.push(`topic write ${prefix}/${serial}/#`);
    lines.push(`topic read +/${serial}/#`);
    lines.push(`topic write +/${serial}/#`);
    lines.push('');
  }

  return lines.join('\n');
}
